---
- name: Install docker software
  package:
      name: docker.io
      state: present
      update_cache: yes

- name: Create Docker conf Directory
  file:
      state: directory
      dest: /etc/docker

- name: setup docker cgroup driver to systemd
  copy:
      src: daemon-json.j2
      dest: /etc/docker/daemon.json
- name: Add an Apt signing key
  apt_key:
      url: "{{ apt_gpgkey }}"
      state: present


- name: Add kubernetes software repository into sources list
  apt_repository:
    repo: "{{ apt_repo_url }}"
    state: present


- name: Install kubelet kubeadm kubectl
  package:
      name: "{{ item }}"
      state: present
  loop: "{{ pkg }}"

- name: Start docker and kubelet
  service:
      name: "{{ item }}"
      state: started
      enabled: yes
  loop: "{{ service }}"

- name: set sysctl
  copy:
      src: k8s.conf
      dest: /etc/sysctl.d/k8s.conf

- name: relode sysctl
  command: "sysctl --system"
  changed_when: false

- name: Disable firewall
  service:
      name: firewalld
      state: stopped
      enabled: no
  ignore_errors: yes

- name: Create token to join
  command: "kubeadm token create  --print-join-command"
  delegate_to: "{{ groups['tag_Name_K8S_Master'][0]  }}"
  register: join_token

- name: join worker Node
  command: "{{ join_token.stdout }}"
  ignore_errors: yes
  changed_when: false

