---
- name: Install docker software
  package:
      name: docker.io
      state: present
      update_cache: yes

- name: Create Docker Conf Directory
  file:
      state: directory
      dest: /etc/docker

- name: setup docker cgroup driver to systemd
  copy:
      src: daemon-json.j2
      dest: /etc/docker/daemon.json

- name: Add an Apt gpg signing key
  apt_key:
      url: "{{ apt_gpgkey }}"
      state: present


- name: Add Kubernetes Software repository into sources list
  apt_repository:
    repo: "{{ apt_repo_url }}"
    state: present


- name: Install kubelet kubeadm kubectl
  package:
      name: "{{ item }}"
      state: present
  loop: "{{ pkg }}"

- name: Start docker and kubelet
  service:
      name: "{{ item }}"
      state: started
      enabled: yes
  loop: "{{ service }}"

- name: configure kubernetes
  copy:
      src: k8s.conf
      dest: /etc/sysctl.d/k8s.conf

- name: sysctl --system
  command: "sysctl --system"
  changed_when: false

- name: Disable firewall
  service:
      name: firewalld
      state: stopped
      enabled: no
  ignore_errors: yes

- name: pull k8s config images
  command: "kubeadm config images pull"
  ignore_errors: yes
  changed_when: False

- name: Initialize the cluster
  command: "{{ kubeadm_init }}"
  ignore_errors: yes

- name: create .kube directory
  file:
      dest: $HOME/.kube
      state: directory
      mode: 0777

- name: Copy admim conf to user's .kube config
  copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes

- name: Install cni pluggin
  shell: "{{ cni_plugin }}"
  ignore_errors: yes

